### ISSUE TITLE
Journey #1: `h-table`

### ISSUE THREAD

**Issue by andrewtpham** [hikaya-io/hakawati#235]
**Is your feature request related to a problem? Please describe.**
In this journey, we would like to make adjustments to the `h-table` component so that we can standardize the way our table functions. We think it will be easier to maintain a single `h-table` component that we can turn on/off functionality when we use it in various implementations in Dots.

Some use cases that can already be achieved in the `h-table` currently are:
- [x] Ability to search the table (built in element)
- [x] Ability to multi-select rows (built in element): https://element.eleme.io/#/en-US/component/table#multiple-select
- [x] Ability to sort by column: https://element.eleme.io/#/en-US/component/table#sorting

Some use cases we would like to add to the `h-table` are:
- [x] Ability to edit a row of data inline the table: https://github.com/hikaya-io/hakawati/issues/46
- [x] Ability to select which columns to hide/display in the table view: https://github.com/hikaya-io/hakawati/issues/233
- [x] Ability to sort the ordering of columns in the table view: https://github.com/hikaya-io/hakawati/issues/233
- [x] #241
- [ ] Ability to resize the column width: https://github.com/hikaya-io/hakawati/issues/234
- [ ] Ability to set a column to `wrap` or `clip` text: https://github.com/hikaya-io/hakawati/issues/237
