### ISSUE TITLE
Adding Controls - v1.0 refactor

### ISSUE THREAD

**Issue by andrewtpham** [hikaya-io/hakawati#337]
# July
- [x] https://github.com/hikaya-io/hakawati/issues/312
- [ ] https://github.com/hikaya-io/hakawati/issues/335
- [x] https://github.com/hikaya-io/hakawati/issues/334
- [x] https://github.com/hikaya-io/hakawati/issues/333
- [x] https://github.com/hikaya-io/hakawati/issues/332
- [x] https://github.com/hikaya-io/hakawati/issues/331
- [x] https://github.com/hikaya-io/hakawati/issues/330

# Should have
- [ ] H-tab
- [ ] NavMenu
- [ ] SideNav
- [ ] Pagination
- [ ] Breadcrumb
- [ ] Steps
- [ ] Drawer
- [ ] Spreadsheet

# Nice to have
- [ ] ColorPicker
- [ ] Avatar
- [ ] Cascader
- [ ] Datepicker
- [ ] Grid
- [ ] Upload
