### ISSUE TITLE
h-spreadsheet: additional features

### ISSUE THREAD

**Issue by ninetteadhikari** [hikaya-io/hakawati#373]
Additional features:

- [x] #386
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/4407063/197537834-19fefffe-1c87-4586-9ac1-e169060b9a46.png">

- [ ] #387
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/4407063/197537969-85fd0967-61cd-40a8-9c32-2d0a62cff94e.png">

![new-spreadsheet-design](https://user-images.githubusercontent.com/13760198/187972551-f364e28c-7119-4876-a60e-37b8225a9249.gif)

- [x] Delete a single row: Click on a single cell and right click
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/4407063/197538113-b1d2ce7d-982e-4557-bc2d-e77bddab5d67.png">

- [x] Delete a single row: Hover on the row index number and click on the checkbox and right click
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/4407063/197538199-707c9248-fae4-499e-90ad-bed35ffe1122.png">

- [x] Delete multiple selected rows: Hover on multiple row index numbers and click on the checkboxes, then right click on one of the selected rows. For all record deletion, display confirmation dialog (as shown when two records are selected)
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/4407063/197538294-885f525c-9744-4a67-a8b5-4de2a2dd2eb3.png">
![Uploading image.png…]()

- [x] #388
- [x] #397 
<img width="725" alt="image" src="https://user-images.githubusercontent.com/4407063/197551408-42067ab5-29a5-4f53-9e27-791ed60c4cbc.png">

![right-click-spreadsheet](https://user-images.githubusercontent.com/4407063/197554544-94ec8411-5fc7-42b9-8161-f85aba16df1e.gif)

- [ ] #389
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/4407063/197538451-c40f1972-3d06-45e2-9a43-a59617551db9.png">

![move-row-spreadsheet](https://user-images.githubusercontent.com/4407063/197524443-e98dc49e-421a-4bf0-a756-3c913fcfa691.gif)

For future enhancements:
- [ ] Add view/edit event/hook (not sure if its done yet) - tap into the logic to `double-click` functionality
- [ ] improvement on setting data type by column
- [ ] allow user to control the width of the column
- [ ] allow devs to merge cells (header cells): example from ElementUI: https://element.eleme.io/#/en-US/component/table#grouping-table-head
- [ ] allow users to freeze/fix certain columns
- [ ] allows user to use `tab` key to switch cells
- [ ] make the '+' add button to be sticky at the bottom when the table is long
- [ ] Select a row height. Provide a set of predefined row heights a user can select:
 - Short (1 line)
 - Medium (2 lines)
 - Tall (4 lines)
 - Extra Tall (6 lines)
<img width="154" alt="image" src="https://user-images.githubusercontent.com/4407063/197536259-c241abc5-c497-454a-95ce-d40af53a6363.png">

- [ ] Summary of sort columns: 
![image](https://user-images.githubusercontent.com/4407063/197536209-b111ee8d-ec63-4c07-a385-d9308abaf202.png)

- [ ] Highlight entire row when right clicking the row

https://github.com/hikaya-io/hakawati/issues/286

_Originally posted by @andrewtpham in https://github.com/hikaya-io/hakawati/issues/355#issuecomment-1280449957_

**Comment by andrewtpham** [comment]
@michaelbukachi tested in `develop`, looks really good. Here's a few more things we can continue working on:

- [ ] When a single checkbox is selected and a user right clicks, the single record menu should display: 

![Image](https://user-images.githubusercontent.com/4407063/197738707-65754613-e9d4-4995-ab13-65585bfd3536.png)

Currently the `delete all selected records` menu displays. This should only display when 2 or more rows are selected.

- [ ] We can add the summary of hide/display columns when a user clicks the `+` icon on the far right column of the spreadsheet
- [ ] We can add the right click when a user clicks the column icon or right clicks on the column header to display the column menu:

![Image](https://user-images.githubusercontent.com/4407063/197739520-7182c618-29f3-43d4-a35a-ec96826a05ac.png)

- [ ] We can add the ability to move columns by dragging and dropping
- [ ] We can add the ability to move rows by dragging and dropping

**Comment by amosnjoroge** [comment]
Additional issues:

- [ ] When deleting multiple records reset the checked state of the checkboxes.
- [ ] Highlight a row by both left and right click. When right clicking highlight the row before the right click pop up is displayed.
- [ ] Tab key navigation to the next cell during edit (nice to have, lower priority)

**Comment by andrewtpham** [comment]
@michaelbukachi for the `hide column` icon, you can use the eye icon `el-icon-view` and we can figure out how to put a slash through it

![Image](https://user-images.githubusercontent.com/4407063/197771399-5bb35ee5-1bdc-43f6-bdd6-420196a88654.png)
